apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  selector:
    matchLabels:
      io.kompose.service: data
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data
    spec:
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: aws-pvc
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: mydatabase
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: saikal1984/quotes-data:v1
        name: db
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: pvc
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
