apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: data-script
  name: data-script
spec:
  selector:
    matchLabels:
      io.kompose.service: data-script
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data-script
    spec:
      containers:
      - image: saikal1984/quotes-data-script:v1
        name: data-script
        resources: {}
      restartPolicy: Always
status: {}
